env:
  browser: true
  es6: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  linebreak-style:
    - error
    - unix
  no-unused-vars:
    - off
ignorePatterns:
  - '**/__*__.js'
  - '**/*.min.js'
  - cypress/
  - jest.config.js
