stages:
  - check
  - deploy

cache:
  paths:
    - node_modules/

lint-jest-e2e:
  stage: check
  image: cypress/base:14
  script:
    - set
    - npm i
    - echo "Building the project"
    - bash bin/build.sh
    - echo "Checking the code quality"
    - bash ./bin/check.sh
  only:
    - merge_requests

pages:
  stage: deploy
  image: node:14
  script:
    - set
    - echo "Deploying public/ folder to GitLab Pages"
    - bash bin/build.sh
  artifacts:
    paths:
      - public
  only:
    - master
