export const types = {
  INIT: 'INIT',

  GET_ITEMS__STARTED: 'GET_ITEMS__STARTED',
  GET_ITEMS__SUCCESS: 'GET_ITEMS__SUCCESS',
  GET_ITEMS_CANCELLED: 'GET_ITEMS_CANCELLED',
  GET_ITEMS__FAILURE: 'GET_ITEMS__FAILURE',

  CHOOSE_ITEM: 'CHOOSE_ITEM',
  REMOVE_FROM_CHOSEN: 'REMOVE_FROM_CHOSEN',

  CLEAR_MESSAGE: 'CLEAR_MESSAGE',
}
