name: Check

on:
  pull_request:
    branches:
      - main

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Instal Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Unit Tests
        run: npm run coverage
      - name: Coverage Report
        if: always() # Also generate the report if tests are failing
        uses: davelosert/vitest-coverage-report-action@v2
      - name: E2E Tests
        run: |
          npx cypress install # FIXME: something is wrong with caching
          npm run e2e

  code-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Instal Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Prettier Check
        run: npm run prettier:check
