name: Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-${{ hashFiles('package-lock.json') }}
            npm-
      - name: Install Dependencies
        run: |
          echo
          echo Using Node $(node -v), NPM $(npm -v)
          echo
          npm ci
      - name: Build
        run: bash bin/build.sh
      - name: Lint
        run: bash bin/lint.sh
      - name: Prettier Check
        run: npm run prettier:check
      - name: Unit Tests
        run: npm run coverage
      - name: Coverage Report
        if: always() # Also generate the report if tests are failing
        uses: davelosert/vitest-coverage-report-action@v1
      - name: E2E Tests
        run: |
          npx cypress install # FIXME: something is wrong with caching
          bash bin/e2e.sh
