name: Publish

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Instal Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish to Github Pages
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout --orphan gh-pages
          git status
          echo
          ls public/
          echo
          git --work-tree public add .
          git --work-tree public commit -m "deploy"
          git push origin HEAD:gh-pages -f
          rm -r public
          git checkout -f main
          git branch -D gh-pages
