name: Publish

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          echo
          echo Using Node $(node -v), NPM $(npm -v)
          echo
          npm ci

      - name: Build
        run: bash bin/build.sh

      - name: Publish to Github Pages
        run: |
          git checkout --orphan gh-pages
          git status
          echo
          ls public/
          echo
          git --work-tree public add .
          git --work-tree public commit --author "GitHub Action <action@github.com>" -m "deploy"
          git push origin HEAD:gh-pages -f
          rm -r public
          git checkout -f main
          git branch -D gh-pages
